/** Canonical Node module names — keep in sync with registerAll.ts order where possible. */
export const NODE_MODULE_NAMES = [
  'system',
  'content',
  'blog',
  'projects',
  'media',
  'users',
  'forms',
  'scheduler',
  'support',
  'payments',
  'orders',
  'products',
  'newsletter',
  'comments',
  'analytics',
  'notifications',
  'automation',
  'webhooks',
  'mail',
  'translate',
  'access',
  'seo',
  'registration',
  'lab',
  'module-manager',
  'ddos',
  'overload',
  'demo',
  'portfolio',
  'template',
] as const;
