import type { LucideIcon } from 'lucide-react'
import {
  Activity, BarChart3, Bell, BriefcaseBusiness, ClipboardList, Cookie, CreditCard,
  Database, FileText, FolderKanban, FormInput, GraduationCap, HeartPulse, HelpCircle,
  Image, Inbox, KeyRound, Layers, LayoutDashboard, LayoutTemplate, Mail, Menu,
  MessageCircle, MessageSquare, Newspaper,   Package, Palette, PanelTop, Puzzle,
  Radar, RefreshCw, Send, Settings, Shield, ShoppingCart, Sparkles, Trash2, Users, Wallet,
  Webhook, Workflow, Wrench, Globe, Bot, Languages, CalendarClock, Boxes,
} from 'lucide-react'
import { toCanonicalAdminPath } from '@/admin/adminBasePath'

/**
 * Manifest icon keys → Lucide. Plugins/ZIP modules use string keys;
 * missing keys fall back to path map, then FileText.
 */
export const navIconRegistry: Record<string, LucideIcon> = {
  users: Users,
  globe: Globe,
  'layout-dashboard': LayoutDashboard,
  briefcase: BriefcaseBusiness,
  graduation: GraduationCap,
  wrench: Wrench,
  layers: Layers,
  folder: FolderKanban,
  'file-text': FileText,
  newspaper: Newspaper,
  settings: Settings,
  'message-square': MessageSquare,
  'message-circle': MessageCircle,
  'help-circle': HelpCircle,
  trash: Trash2,
  'trash-2': Trash2,
  'panel-top': PanelTop,
  'layout-template': LayoutTemplate,
  menu: Menu,
  mail: Mail,
  image: Image,
  activity: Activity,
  heart: HeartPulse,
  palette: Palette,
  database: Database,
  key: KeyRound,
  webhook: Webhook,
  'shopping-cart': ShoppingCart,
  'credit-card': CreditCard,
  shield: Shield,
  'refresh-cw': RefreshCw,
  bell: Bell,
  workflow: Workflow,
  send: Send,
  sparkles: Sparkles,
  package: Package,
  cookie: Cookie,
  radar: Radar,
  wallet: Wallet,
  'bar-chart-3': BarChart3,
  'clipboard-list': ClipboardList,
  inbox: Inbox,
  'form-input': FormInput,
  puzzle: Puzzle,
  bot: Bot,
  languages: Languages,
  'calendar-clock': CalendarClock,
  boxes: Boxes,
}

const pathIcons: Record<string, LucideIcon> = {
  '/admin/profile': Users,
  '/admin/social-links': Globe,
  '/admin/statistics': LayoutDashboard,
  '/admin/experience': BriefcaseBusiness,
  '/admin/education': GraduationCap,
  '/admin/skills': Wrench,
  '/admin/skill-categories': Layers,
  '/admin/projects': FolderKanban,
  '/admin/blog': Newspaper,
  '/admin/services': BriefcaseBusiness,
  '/admin/testimonials': MessageSquare,
  '/admin/trash': Trash2,
  '/admin/hero': PanelTop,
  '/admin/pages': LayoutTemplate,
  '/admin/homepage': Globe,
  '/admin/navigation': Menu,
  '/admin/footer': PanelTop,
  '/admin/contact-info': Mail,
  '/admin/messages': Inbox,
  '/admin/media': Image,
  '/admin/activity': Activity,
  '/admin/system': HeartPulse,
  '/admin/seo': Radar,
  '/admin/redirects': RefreshCw,
  '/admin/site-settings': Settings,
  '/admin/theme': Palette,
  '/admin/email': Mail,
  '/admin/mail': Mail,
  '/admin/backup': Database,
  '/admin/updates': RefreshCw,
  '/admin/password': KeyRound,
  '/admin/plugins': Puzzle,
  '/admin/modules': Package,
  '/admin/forms': FormInput,
  '/admin/form-submissions': ClipboardList,
  '/admin/analytics': BarChart3,
  '/admin/automations': Workflow,
  '/admin/scheduler': CalendarClock,
  '/admin/notifications': Bell,
  '/admin/comments': MessageSquare,
  '/admin/support': MessageCircle,
  '/admin/support/faq': HelpCircle,
  '/admin/translate': Languages,
  '/admin/lab': Sparkles,
  '/admin/ddos': Shield,
  '/admin/overload': Activity,
  '/admin/webhooks': Webhook,
  '/admin/products': ShoppingCart,
  '/admin/orders': ShoppingCart,
  '/admin/payments': CreditCard,
  '/admin/users': Users,
  '/admin/newsletter/subscribers': Users,
  '/admin/newsletter/campaigns': Send,
  '/admin/cookie-consent': Cookie,
  '/admin/indexnow': Radar,
  '/admin/ai-content-optimizer': Sparkles,
  '/admin/jasefly-character': Bot,
}

export function resolveNavIcon(path: string, iconKey?: string): LucideIcon {
  if (iconKey) {
    const byKey = navIconRegistry[iconKey]
    if (byKey) return byKey
  }
  const canon = toCanonicalAdminPath(path)
  return pathIcons[canon] ?? pathIcons[path] ?? FileText
}
