/** @deprecated Import from `@/shared/ui` — kept for backward compatibility */
export {
  Container,
  Section,
  Grid,
  Button,
  GhostButton,
  GlassPanel,
  SurfacePanel,
  Card,
  Skeleton,
  EmptyState,
  RichText,
  MediaImage,
  ImageLightbox,
  SectionHeading,
  Timeline,
  Field,
  Modal,
} from '@/shared/ui'
