# One-click setup on a new PC: download tools if needed, npm install, DB (MySQL or SQLite).
# Entry: setup.bat

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\bootstrap-tools.ps1"
. "$PSScriptRoot\dev-lib.ps1"

$Host.UI.RawUI.WindowTitle = 'Jasefly CMS - Setup'
Clear-Host
Write-Host ''
Write-Host '  Jasefly CMS - auto setup (new PC)' -ForegroundColor White
Write-Host '  ------------------------------------' -ForegroundColor DarkGray
Write-Host '  Downloads Node/PHP if missing, installs deps,' -ForegroundColor DarkGray
Write-Host '  uses MySQL when available, otherwise SQLite.' -ForegroundColor DarkGray
Write-Host ''

Ensure-DevDir
Ensure-StorageDirs
New-Item -ItemType Directory -Path (Join-Path $Root 'backend\storage\sqlite') -Force | Out-Null

Write-Info 'Checking / downloading Node.js and PHP...'
$tools = Ensure-DevTools
$nodeExe = $tools.Node
$phpExe = $tools.Php
Use-ToolsPath

$nodeVer = & $nodeExe -v
$npmCmd = Join-Path (Split-Path $nodeExe -Parent) 'npm.cmd'
if (-not (Test-Path $npmCmd)) { $npmCmd = 'npm' }
Write-Ok "Node $nodeVer"
Write-Ok "PHP $(& $phpExe -r 'echo PHP_VERSION;')"

$db = Read-DbEnv
$driver = 'sqlite'
$vitePort = 5173
$phpPort = 8080
$sqlitePath = 'storage/sqlite/cms.sqlite'

Write-Info 'Probing MySQL...'
$probe = Test-MysqlConnection $db $phpExe
if ($probe.ok) {
  $driver = 'mysql'
  Write-Ok "MySQL OK ($($db.DB_HOST)/$($db.DB_NAME))"
} else {
  Write-Warn "MySQL unavailable: $($probe.error)"
  Write-Warn 'Falling back to SQLite (backend\storage\sqlite\cms.sqlite) - no DB server needed'
  $driver = 'sqlite'
}

Write-DbEnv $db
$jwt = Get-OrCreateJwt
$configPath = Join-Path $Root 'backend\config\config.local.php'

function Write-SqliteConfig([string]$Jwt, [int]$VitePort, [string]$SqliteRel) {
  @(
    '<?php'
    'declare(strict_types=1);'
    '/** Auto-generated by setup.bat (SQLite mode). */'
    'return array('
    "    'app_name' => 'Jasefly CMS',"
    "    'app_url' => 'http://localhost:$VitePort',"
    "    'app_env' => 'local',"
    "    'jwt_secret' => '$Jwt',"
    "    'jwt_ttl' => 3600,"
    "    'refresh_ttl' => 604800,"
    "    'cors_origins' => 'http://localhost:$VitePort,http://127.0.0.1:$VitePort',"
    "    'upload_max_mb' => 10,"
    "    'db_driver' => 'sqlite',"
    "    'db_path' => '$SqliteRel',"
    "    'db_charset' => 'utf8mb4',"
    ');'
  ) | Set-Content -Path $configPath -Encoding ASCII
}

if ($driver -eq 'sqlite') {
  Write-SqliteConfig $jwt $vitePort $sqlitePath
} else {
  Write-BackendConfig $db $vitePort $jwt
  $raw = Get-Content $configPath -Raw
  if ($raw -notmatch 'db_driver') {
    $raw = $raw -replace 'return array\(', "return array(`r`n    'db_driver' => 'mysql',"
    Set-Content -Path $configPath -Value $raw -Encoding UTF8
  }
}
Write-Ok "config.local.php ($driver)"
Write-FrontendEnv $phpPort $vitePort
Write-Ok 'frontend/.env.development.local'

Write-Info 'npm install (frontend)...'
Push-Location (Join-Path $Root 'frontend')
try {
  & $npmCmd install
  if ($LASTEXITCODE -ne 0) { throw 'npm install frontend failed' }
} finally { Pop-Location }
Write-Ok 'frontend/node_modules'

$mcpPkg = Join-Path $Root 'mcp-cms\package.json'
if (Test-Path $mcpPkg) {
  Write-Info 'npm install (mcp-cms)...'
  Push-Location (Join-Path $Root 'mcp-cms')
  try {
    & $npmCmd install
    if ($LASTEXITCODE -ne 0) { Write-Warn 'mcp-cms npm install failed (optional for local site)' }
    else { Write-Ok 'mcp-cms/node_modules' }
  } finally { Pop-Location }
}

$lock = Join-Path $Root 'backend\storage\.installed'
if (Test-Path $lock) {
  Write-Ok 'DB already installed (storage/.installed) - skip schema'
} else {
  Write-Info "Installing schema + demo ($driver)..."
  $cors = "http://localhost:$vitePort,http://127.0.0.1:$vitePort"
  Push-Location (Join-Path $Root 'backend')
  try {
    if ($driver -eq 'sqlite') {
      & $phpExe install.php `
        '--driver=sqlite' `
        "--sqlite_path=$sqlitePath" `
        "--url=http://localhost:$vitePort" `
        "--cors=$cors" `
        '--email=admin@example.com' `
        '--demo=1' `
        '--keep=1'
    } else {
      $passArg = if ($db.DB_PASS) { "--pass=$($db.DB_PASS)" } else { '--pass=' }
      & $phpExe install.php `
        '--driver=mysql' `
        "--host=$($db.DB_HOST)" `
        "--name=$($db.DB_NAME)" `
        "--user=$($db.DB_USER)" `
        $passArg `
        "--url=http://localhost:$vitePort" `
        "--cors=$cors" `
        '--email=admin@example.com' `
        '--demo=1' `
        '--keep=1'
    }
    if ($LASTEXITCODE -ne 0) { throw 'install.php failed' }
  } finally { Pop-Location }

  $jwt = Get-OrCreateJwt
  if ($driver -eq 'sqlite') {
    Write-SqliteConfig $jwt $vitePort $sqlitePath
  } else {
    Write-BackendConfig $db $vitePort $jwt
  }
  Write-Ok 'DB schema + demo content'
}

@(
  "NODE_EXE=$nodeExe"
  "PHP_EXE=$phpExe"
  "DB_DRIVER=$driver"
) | Set-Content -Path (Join-Path $DevDir 'tools.env') -Encoding ASCII

Write-Host ''
Write-Host '  ======================================' -ForegroundColor Green
Write-Host '  READY - you can start the site.' -ForegroundColor Green
Write-Host '  ======================================' -ForegroundColor Green
Write-Host ''
Write-Host "  DB:       $driver" -ForegroundColor White
Write-Host '  Admin:    admin@example.com' -ForegroundColor White
Write-Host '  Password: Admin123!' -ForegroundColor White
Write-Host '  Run:      start.bat' -ForegroundColor Cyan
Write-Host ''
if ($tools.UsedPortableNode -or $tools.UsedPortablePhp) {
  Write-Host '  Portable tools are in .tools\ (safe to delete after installing system Node/PHP).' -ForegroundColor DarkGray
  Write-Host ''
}

$ans = Read-Host 'Start the site now? [Y/n]'
if ($ans -eq '' -or $ans -match '^[Yy]') {
  Write-Info 'Starting start.bat...'
  $env:PORTFOLIO_NODE = $nodeExe
  $env:PORTFOLIO_PHP = $phpExe
  & cmd /c "`"$Root\start.bat`""
}
